import Head from "next/head";
import Layout from "../components/Layout";
import Shops from "../components/Shops";

export default function Home({products}) {
  return (
    <div>
      <Head>
        <title>Next-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Layout>
         <Shops products={products} />
       </Layout>
    </div>
  );
}


export async function getStaticProps () {
  const res = await fetch('https://fakestoreapi.com/products');
  const products = await res.json();
  return{
    props:{
      products,
    }
  }
}